### ISSUE TITLE
no graphic view in half screen mode

### ISSUE THREAD

**Issue by djabmal** [ExpressLRS/ElrsTelemWidget#7] opened 2023-02-28 15:51 UTC
i have the graphic in full size screen but not in in half screen size? i have edgetx 2.8.1

**Comment by CapnBry** [comment] 2023-02-28 16:23
Update to the latest version, this should have been fixed in v4 back in December (but get v5 released today). If it is not, you'll need to be more specific.

**Comment by djabmal** [comment] 2023-02-28 16:53
i would like to have the graphic view in half screen 
![IMG_1413 - copie](https://user-images.githubusercontent.com/73159961/221921995-0307237e-5483-49dd-b1fb-275b9d002806.jpg)
![IMG_1414 - copie](https://user-images.githubusercontent.com/73159961/221922014-0d708a9b-a1b8-46b5-aeac-acf8cd349260.jpg)

**Comment by CapnBry** [comment] 2023-02-28 16:55
Like I said. This has been fixed already. :-D

**Comment by djabmal** [comment] 2023-02-28 16:56
but how can i have it ihave the latest version and still its not working

**Comment by CapnBry** [comment] 2023-02-28 16:59
Maybe you didn't copy the files to the correct place? LQ and Signal are on the same line which means the widget thinks it is running in a smaller space than the half screen size, which was fixed in v4 onward.

**Comment by djabmal** [comment] 2023-02-28 17:06
i put it in the widget file
[WIDGETS.zip](https://github.com/ExpressLRS/ElrsTelemWidget/files/10852867/WIDGETS.zip)
tell me if i am wrong thanks

**Comment by CapnBry** [comment] 2023-02-28 17:51
Oh #$%^#. EdgeTX 2.8.1changes the size of the widget area by a few pixels now depending on what options are enabled, completely not mentioned at all in the release notes. I'll see about fixing this.

**Comment by djabmal** [comment] 2023-02-28 18:53
great thanks

**Comment by CapnBry** [comment] 2023-03-01 15:12
Can you try release v6 and see how that goes?

**Comment by djabmal** [comment] 2023-03-01 15:16
sure i will do it now

**Comment by djabmal** [comment] 2023-03-01 15:23
great job thanks
![IMG_1418 - copie](https://user-images.githubusercontent.com/73159961/222183790-73916c9a-fdfa-4e2a-989d-f75253c2f2a7.jpg)

**Comment by CapnBry** [comment] 2023-03-01 15:31
Great! I apologize for doubting you at first since I couldn't reproduce it, but it seems the widget isn't notified of size changes without rebooting so it worked fine for me in every configuration... until I rebooted.

**Closed by CapnBry** 2023-03-01 15:31 UTC

**Comment by djabmal** [comment] 2023-03-01 16:35
no problem i was doubting too ... thanks anyway this is a fantastic app for ELRS
